# Generated by Django 5.0.6 on 2024-06-26 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mess_contact_no_alter_mess_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='contact_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
