# Generated by Django 5.0.6 on 2024-06-26 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mess_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mess',
            name='delivery',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mess',
            name='rating',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
